# include $(top_srcdir)/automake/compile.am
# 
# include_HEADERS = fdt.h libfdt.h libfdt_env.h
# 
# noinst_LIBRARIES = libfdt.a
# 
# libfdt_a_CPPFLAGS = $(AM_CPPFLAGS) -I$(srcdir)
# libfdt_a_SOURCES =
obj-y += fdt_addresses.o
obj-y += fdt.o
obj-y += fdt_empty_tree.o
obj-y += fdt_ro.o
obj-y += fdt_rw.o
obj-y += fdt_strerror.o
obj-y += fdt_sw.o
obj-y += fdt_wip.o
# 
# include $(srcdir)/preinstall.am
# include $(top_srcdir)/automake/local.am
