obj-y += version.o
CFLAGS_version.o = \
-B../../../lib/ -B../../../arm920/lib/ -specs $(srctree)/c/src/lib/libbsp/arm/smdk2410/bsp_specs -qrtems \
-DPACKAGE_NAME=\"rtems-c-src\" -DPACKAGE_TARNAME=\"rtems-c-src\" -DPACKAGE_VERSION=\"4.11.99.0\" -DPACKAGE_STRING=\"rtems-c-src\ 4.11.99.0\" -DPACKAGE_BUGREPORT=\"https://devel.rtems.org/newticket\" -DPACKAGE_URL=\"\" $(INCLUDE) -DRTEMS_BSP=\"arm920\"

