obj-n += arm-a9mpcore-clock-config.o
obj-n += arm-a9mpcore-smp.o
obj-n += arm-cp15-set-exception-handler.o
obj-n += arm-cp15-set-ttb-entries.o
obj-n += arm-gic-irq.o
obj-n += arm-pl011.o
obj-n += arm-pl050.o
obj-n += arm-pl111-fb.o
obj-n += mminit.o

obj-y += abort/
obj-n += armv7m/
obj-n += comm/
obj-n += lpc/
obj-n += start/
obj-n += startup/

subdir-ccflags-y := -DCPU_S3C2410 -specs $(srctree)/c/src/lib/libbsp/arm/smdk2410/bsp_specs
subdir-asflags-y :=

