# include $(top_srcdir)/automake/compile.am
# 
# if LIBDRVMGR
# 
# EXTRA_DIST=
# 
# noinst_LIBRARIES = libdrvmgr.a
# 
# libdrvmgr_a_SOURCES = drvmgr.c
# libdrvmgr_a_SOURCES += drvmgr.h
# libdrvmgr_a_SOURCES += drvmgr_by_name.c
# libdrvmgr_a_SOURCES += drvmgr_by_id.c
# libdrvmgr_a_SOURCES += drvmgr_dev_by_name.c
# libdrvmgr_a_SOURCES += drvmgr_drvinf.c
# libdrvmgr_a_SOURCES += drvmgr_init.c
# libdrvmgr_a_SOURCES += drvmgr_confdefs.h
# libdrvmgr_a_SOURCES += drvmgr_for_each_dev.c
# libdrvmgr_a_SOURCES += drvmgr_for_each_list_dev.c
# libdrvmgr_a_SOURCES += drvmgr_func.c
# libdrvmgr_a_SOURCES += drvmgr_func_call.c
# libdrvmgr_a_SOURCES += drvmgr_list.c
# libdrvmgr_a_SOURCES += drvmgr_list.h
# libdrvmgr_a_SOURCES += drvmgr_lock.c
# libdrvmgr_a_SOURCES += drvmgr_print.c
# libdrvmgr_a_SOURCES += drvmgr_res.c
# libdrvmgr_a_SOURCES += drvmgr_rw.c
# libdrvmgr_a_SOURCES += drvmgr_translate.c
# libdrvmgr_a_SOURCES += drvmgr_translate_check.c
# libdrvmgr_a_SOURCES += drvmgr_unregister.c

CONFIG_LIBDRVMGR := y
obj-$(CONFIG_LIBDRVMGR) += drvmgr.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_by_name.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_by_id.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_dev_by_name.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_drvinf.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_init.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_for_each_dev.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_for_each_list_dev.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_func.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_func_call.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_list.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_lock.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_print.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_res.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_rw.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_translate.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_translate_check.o
obj-$(CONFIG_LIBDRVMGR) += drvmgr_unregister.o

# 
# endif
# 
# include $(top_srcdir)/automake/local.am
# 