obj-y += cs8900.o
obj-y += dec21140.o
obj-y += dwmac-1000-core.o
obj-y += dwmac-1000-dma.o
obj-y += dwmac-1000-ethernet-mac-ops.o
obj-y += dwmac.o
obj-y += dwmac-core.o
obj-y += dwmac-desc-com.o
obj-y += dwmac-desc-enh.o
obj-y += elnk.o
obj-y += greth.o
obj-y += i82586.o
obj-y += if_dc.o
obj-y += if_fxp.o
obj-y += open_eth.o
obj-y += smc91111.o
obj-y += sonic.o

subdir-ccflags-y := \
	-D__INSIDE_RTEMS_BSD_TCPIP_STACK__ \
	-DPACKAGE_BUGREPORT=\"https://devel.rtems.org/newticket\" \
	-DPACKAGE_NAME=\"rtems-c-src\" \
	-DPACKAGE_STRING=\"rtems-c-src\" \
	-DPACKAGE_TARNAME=\"rtems-c-src\" \
	-DPACKAGE_URL=\"\" \
	-DPACKAGE_VERSION=\"4.11.99.0\"

