# include $(top_srcdir)/automake/multilib.am
# include $(top_srcdir)/automake/compile.am
# 
# noinst_LIBRARIES = libblock.a
obj-y += bdbuf.o
obj-y += blkdev.o
obj-y += blkdev-imfs.o
obj-y += blkdev-ioctl.o
obj-y += blkdev-ops.o
obj-y += blkdev-print-stats.o
obj-y += blkdev-blkstats.o
obj-y += diskdevs.o
obj-y += diskdevs-init.o
obj-y += flashdisk.o
obj-y += ramdisk-driver.o
obj-y += ramdisk-init.o
obj-y += ramdisk-config.o
obj-y += ramdisk-register.o
obj-y += ide_part_table.o
obj-y += nvdisk.o
obj-y += nvdisk-sram.o
obj-y += bdpart-create.o
obj-y += bdpart-dump.o
obj-y += bdpart-mount.o
obj-y += bdpart-read.o
obj-y += bdpart-register.o
obj-y += bdpart-sort.o
obj-y += bdpart-write.o
obj-y += media-path.o
obj-y += media.o
obj-y += media-server.o
obj-y += media-desc.o
obj-y += media-dev-ident.o
obj-y += sparse-disk.o
#     include/rtems/bdbuf.h include/rtems/blkdev.h \
#     include/rtems/diskdevs.h include/rtems/flashdisk.h \
#     include/rtems/ramdisk.h include/rtems/nvdisk.h include/rtems/nvdisk-sram.h \
#     include/rtems/ide_part_table.h
# 
# include $(top_srcdir)/automake/local.am
