# include $(top_srcdir)/automake/compile.am
# 
# if LIBNETWORKING
# project_lib_LIBRARIES = libftpd.a
obj-y += ftpd.o
# endif
# 
# include $(srcdir)/preinstall.am
# include $(top_srcdir)/automake/local.am
